name: Concurrency 

on: [push] 
concurrency: 
  group: ${github.workflow} - ${github.ref} 
  cancel-in-progress: true 

jobs: 
  hello: 
    runs-on: ubuntu-latest 
    steps: 
    - name: step1
      run: sleep20   
 