name: Dependency 

on: [push] 
jobs: 
   job-1: 
      runs-on: ubuntu-latest 
      steps: 
      - name: step1 
        run: echo "Hi i am from job-1" 
   job-2:
      needs: job-1
      runs-on: ubuntu-latest 
      steps: 
      - name: step2 
        run: echo "Hi i am from job-2" 
   job-3: 
      needs: job-2 
      runs-on: ubuntu-latest 
      steps: 
      - name: step3 
        run: echo "Hi i am from job-3" 
   job-4: 
      runs-on: ubuntu-latest
      steps: 
      - name: step4 
        run: echo "Hi i am from job-4"                