name: Parallel 

on: [push] 
jobs: 
  job-1: 
    runs-on: ubuntu-latest 
    steps: 
    - name: step1 
      run: echo "I am from job-1" 
  job-2: 
    runs-on: ubuntu-latest 
    steps: 
    - name: step2 
      run: echo "I am from job-2" 
  job-3: 
    runs-on: 
    steps: 
    - name: step3
      run: echo "I am form job-3"        